### ISSUE TITLE
No response from localhost:3000

### ISSUE THREAD

**Issue by anil1712** [cgreening/node-seoserver#3]
Hi, I have installed all dependencies but I am not getting any response from server, can you please tell me how to pass dynamic url with some querystring then phantomjs will render the content into an html file. Here are the output after typing `node seoserver.js` 

> node seoserver.js
>     port : 3000
>     baseURL : http://www.amazon.com
>     accessLogFile : access.log
>     desktopPhantomScript : render_desktop_phantom.js
>     mobilePhantomScript : render_mobile_phantom.js
>     phantomTimeout : 10000
>     resourceTimeout : 5000
>     Listening on port : 3000

**Comment by cgreening** [comment]
You should get a copy of the amazon.com homepage when you point your browser to http://localhost:3000

If you want to put that content into a file then you can use curl or wget, but if you just need an html file you might be better off using phantomjs directly.

**Comment by anil1712** [comment]
http://localhost:3000 is saying `Oops! Google Chrome could not connect to localhost:3000`

**Comment by anil1712** [comment]
It seems my system has some problem with nodejs. I tried the same with other system, its working fine. Thanks for the comments, but can you please tell me how to provide dynamic urls. because config/default.js has static urls, how can I provide urls on run time?

**Comment by cgreening** [comment]
That's not currently possible with the current code - it's very much designed to pull content from one site. You should be able to modify the code so that you can pass in a header with the host you want to access.

What are you actually trying to achieve - maybe there is an easier way of doing what you want.

**Comment by anil1712** [comment]
actaully I have ajax based website and whenever google bot requests in my site then I want to redirect the bot to another port ie. `3000` and the phantomjs code will responsible to render the HTML content from the requests

**Comment by cgreening** [comment]
Rather than redirect the bot you should just send it the content from the seoserver.

In nginx you would do this:

location / {
    proxy_pass defaultProxy;
    if ($http_user_agent ~\* bot)  {
        proxy_pass  http://localhost:3000;
    }

This will pass any requests from a bot user agent to localhost:3000 and will automatically add the request uri.

So for example a request to your website - http://www.mywebsite.com/page/data?test=abc

Gets passed on as

http://localhost:3000/page/data?test=abc

The seoserver then makes the request for http://www.mywebsite.com/page/data?test=abc and renders it as offline content and serves it up to the bot.

**Comment by anil1712** [comment]
ok will try this, Thanks for your comments.
